default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rantly_development

test:
  <<: *default
  database: rantly_test

production:
  <<: *default
  database: rantly_production
